import uuid from 'node-uuid';

export const SAMPLE_DOC2 = {
  uuid: uuid.v4(),
  name: 'default',
  pageIndex: 0,
  changed: false,
  pages: [
    {name: '1.1b', content: '༄༅།།བསོད་ནམས་ཡེ་ཤེས་ཚོགས་གཉིས་', destImagePath: ''},
    {name: '1.2b', content: 'ལྡན་ཟླ་བའི་བཞིན་རས་ཅན། །སྤྲིན་དཀར་ཕུང་པོའི་གོས་ཟུང་གིས་མཛེས་མ། ',
      destImagePath: 'assets/images/dulwa-001-002b.jpg'},
    {name: '1.2a', content: 'དད་པའི་འཇའ་ཚོན་དབུས་ནས་གར་བྱེད་པོ། །སྐལ་བཟང་རྣམས་ཀྱི་གཙུག་གི་ཤར་རི་ལ། ',
      destImagePath: 'assets/images/dulwa-001-002a.jpg'}
  ],
  chunk: 'By Curtis Skinner\nRelated Stories\nProtesters rally at California jail after deputies arrested Reuters\nThree California jail deputies arrested over inmate\'s beating death Reuters\nRally held after Santa Clara County jail inmate\'s death Associated Press\nJailers arrested in death of mentally ill inmate: Will case prompt reforms? Christian Science Monitor\nCalifornia guard says he did not touch inmate found dead Associated Press\n SAN FRANCISCO (Reuters) - Three corrections deputies were charged with murder on Tuesday in connection with the fatal beating of a mentally ill inmate at a California jail last month, officials said.\nMatthew Farris, Jereh Lubrin and Rafael Rodriguez were arrested on Thursday, just over a week after the killing of 31-year-old prisoner Michael James Tyree at the Santa Clara County\'s main jail in San Jose.\n"These men violated the law, human dignity, and the job that they were sworn to do," Santa Clara County District Attorney Jeff Rosen said in a statement.\n"They may have thought that their violence, enacted late at night in the obscurity of a jail cell and against a helpless and mentally ill inmate, was invisible. Today we see it for all of its brutality," he added.\nThe three deputies did not enter pleas at Tuesday\'s arraignment, according to the district attorney\'s office. They could face life in prison if convicted.\nSanta Clara County Sheriff Laurie Smith said Tyree was in a protective custody wing of the county\'s main jail the night of Aug. 26, after his arrest on misdemeanor drug possession and theft charges.\n The three deputies were conducting a clothing search on the wing before entering Tyree\'s single-person cell, she said. During the vicious beating, numerous inmates could hear Tyree screaming, "I\'m sorry. I\'m sorry. Stop," the district attorney\'s office said.Smith said no one else had any contact with Tyree before Lubrin came back to discover his naked body, which was covered in feces and vomit, about an hour later.The county medical examiner-coroner said Tyree died of internal bleeding from multiple blunt force injuries. An attorney for Tyree\'s family said he suffered from mental illness and was being housed in the jail because space at a mental health facility was not available.The three were also charged with assault under color of authority for beating another inmate just minutes before attacking Tyree, the district attorney\'s office said.Smith said last week the men were arrested also on suspicion of conspiracy, but prosecutors did not present those charges.Rodriguez told the San Jose Mercury News in a jailhouse interview on Saturday that he was innocent.\n"It sucks being in here for something I didn\'t do," he said, according to the newspaper.\n (Reporting by Curtis Skinner; Editing by Mohammad Zargham)'
};
