sudo: required
language: node_js
node_js:
  - 8.4.0
cache: yarn
before_install:
- sudo add-apt-repository -y ppa:ubuntu-wine/ppa
- sudo apt-get -y install wine1.8 winetricks
- npm i -g electron-packager@9.0.0
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.28.4
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- test $TRAVIS_BRANCH = "master" && yarn build
addons:
  artifacts:
    branch: master
    paths:
    - $(ls ./zips/*.zip | tr "\n" ":")
