language: node_js
matrix:
  include:
    - os: osx
      osx_image: xcode9
node_js:
  - 9.2.0
cache: yarn
before_install:
  - npm i -g npm@5.5.1
  - brew update
  - npm i -g electron-packager@9.0.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - brew install awscli
script:
  - test $TRAVIS_BRANCH = "master" && yarn build-mac && yarn upload-mac
